# Generated by Django 5.2.1 on 2025-06-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('aciklama', models.TextField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('islem_turu', models.CharField(choices=[('GELİR', 'Gelir'), ('GİDER', 'Gider'), ('DEVİR', 'Gün Sonu Devir')], max_length=10)),
            ],
        ),
    ]
